# Generated by Django 3.2.5 on 2021-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210727_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='blog.Catergory', verbose_name='دسته بندی'),
        ),
    ]
